services:
  - type: web
    name: obj-det-assistive
    runtime: python
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.1
      - key: TORCH_HOME
        value: /opt/render/project/data/torch
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 -k gthread -t 120 -b 0.0.0.0:$PORT app:app
    autoDeploy: true
    disks:
      - name: model-cache
        mountPath: /opt/render/project/data
        sizeGB: 2
